//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JarBird
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int IDOrders { get; set; }
        public string DeliveryAddress { get; set; }
        public Nullable<int> IDUser { get; set; }
        public Nullable<int> IDStatus { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> IDProduct { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> PriceInOrder { get; set; }
        public Nullable<double> LineTotal { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual Users Users { get; set; }
    }
}
