//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JarBird
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.Korzina = new HashSet<Korzina>();
            this.Orders = new HashSet<Orders>();
        }
    
        public int IDProduct { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> IDProductType { get; set; }
        public string Description { get; set; }
        public string Composition { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> DiscountProcent { get; set; }
        public Nullable<bool> IsDiscountActive { get; set; }
        public Nullable<int> MinStock { get; set; }
        public Nullable<int> QuantityInStock { get; set; }
        public string ImagePath { get; set; }
    
        public virtual ICollection<Korzina> Korzina { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ProductTypes ProductTypes { get; set; }
    }
}
